import { Link } from "react-router-dom";
import icons from "../../../icons/icons";

const headerData = [
    {
        title: "נדל״ן",
        row1: [
            { text: <Link to="/forSale">דירות למכירה</Link> },
            { text: "דירות להשכרה" },
            { text: "שותפים" },
            { text: "מסחרי" },
            { text: "חיפוש על גבי מפה" },
        ],
        row2: [
            { icon: icons.hammer, text: "כונס נכסים" },
            { icon: icons.hammer, text: "כונס נכסים" },
            { icon: icons.chart, text: "מדד הנדל״ן" },
            { icon: icons.home, text: "יד1 דירות חדשות" },
            { icon: icons.calculator, text: "הערכת שווי הנכס" },
            { icon: icons.home, text: "משרדי תיווך בישראל" },
        ],
    },
    {
        title: "רכב",
        row1: [
            { text: "פרטי" },
            { text: "מסחרי" },
            { text: "ג׳יפים" },
            { text: "אופונעים" },
            { text: "קטנועים" },
            { text: "מיוחדים" },
            { text: "אביזרים" },
            { text: "משאיות" },
            { text: "כלי שיט" },
        ],
        row2: [
            { icon: icons.car, text: "קטלוג רכבים" },
            { icon: icons.car, text: "מחירון רכב" },
            { icon: icons.hammer, text: "מכרזים וכינוס" },
            { icon: icons.calculator, text: "מימון רכב" },
        ],
    },
    {
        title: "יד שנייה ",
        row1: [
            { text: "כל המוצרים" },
            { text: "מוצרי חשמל" },
            { text: "ריהוט" },
            { text: "עסקים למכירה" },
            { text: "ספורט" },
            { text: "סלולרי" },
            { text: "לתינוק ולילד" },
            { text: "הכל בחינם!" },
        ],
        row2: [
            { text: "קונסולות משחק" },
            { text: "מחשבים וציוד נלווה" },
            { text: "לגינה" },
            { text: "אופנה וטיפוח" },
            { icon: icons.gift, text: "יד2 מכל הלב" },
        ],
    },
    {
        title: "דרושים IL",
        row1: [
            { text: "חיפוש עבודה" },
            { text: "פרסום משרות" },
            { text: "כתובת קורות חיים" },
            { text: "אודות החברה" },
            { text: "דרושים הייטק" },
            { text: "דרושים סטודנטים" },
            { text: "משרות ללא קו״ח" },
            { text: "כספים" },
            { text: "מכירות" },
            { text: "שירות לקוחות" },
        ],
        row2: [
            { text: "אדמיניסטרציה" },
            { text: "מהנדסים" },
            { text: "תחבורה" },
            { text: "מסעדנות/תיירות" },
            { text: "אבטחה" },
            { text: "בריאות" },
            { text: "בעלי מקצוע" },
            { text: "הדרכה/הוראה" },
            { text: "שיווק" },
            { text: "לתחומים נוספים" },
        ],
    },
    {
        title: "עסקים למכירה",
        row1: [
            { text: "בתי קפה ומסעדות" },
            { text: "זכיינות" },
            { text: "קווי חלוקה" },
            { text: "הזדמנויות עסקיות" },
            { text: "מינימרקטים וסופרמרקטים" },
            { text: "קיוסקים ופיצוציות" },
            { text: "לכל העסקים" },
        ],
    },
    {
        title: "חיות מחמד",
        row1: [
            { text: "כלבים" },
            { text: "חתולים" },
            { text: "תוכים ובעלי כנף" },
            { text: "דגים" },
            { text: "זוחלים" },
            { text: "מכרסמים" },
            { text: "סוסים" },
            { text: "תרנגולים" },
            { text: "חיות משק" },
            { text: "חמוסים" },
        ],
    },
    {
        title: "בעלי מקצוע",
        row1: [
            { text: "מכוני בדיקה ורישוי לרכב" },
            { text: "רחיצת רכב" },
            { text: "שמאי מקרקעין" },
            { text: "חומרי בניין" },
            { text: "אינסטלטור" },
            { text: "חשמלאים" },
            { text: "שיפוצים" },
            { text: "הובלות" },
            { text: "רהיטים" },
            { text: "חברות ניקיון ואחזקה" },
            { text: "לכל בעלי המקצוע" },
        ],
    },
    {
        title: "עוד...",
        row1: [
            { text: "תיירות ונופש" },
            { text: "לימודים" },
            { text: "מגזין יד2" },
        ],
    },
];

export default headerData;
