import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import {
    faUser,
    faHome,
    faSignInAlt,
    faSignOutAlt,
    faEnvelope,
    faInfoCircle,
    faSearch,
    faFilter,
    faChevronDown,
    faChevronRight,
    faHeart,
    faShoppingCart,
    faCheck,
    faTruck,
    faEye,
    faShoppingBasket,
    faPlus,
    faCreditCard,
    faTimes,
    faRedoAlt,
    faShieldAlt,
    faQuestionCircle,
    faMapMarkerAlt,
    faBars,
} from "@fortawesome/free-solid-svg-icons";
import { faCcVisa, faPaypal } from "@fortawesome/free-brands-svg-icons";

const icons = {
    user: <FontAwesomeIcon icon={faUser} />,
    home: <FontAwesomeIcon icon={faHome} />,
    logIn: <FontAwesomeIcon icon={faSignInAlt} />,
    logOut: <FontAwesomeIcon icon={faSignOutAlt} />,
    contactUs: <FontAwesomeIcon icon={faEnvelope} />,
    help: <FontAwesomeIcon icon={faInfoCircle} />,
    search: <FontAwesomeIcon icon={faSearch} />,
    fliter: <FontAwesomeIcon icon={faFilter} />,
    downArrow: <FontAwesomeIcon icon={faChevronDown} />,
    rightArrow: <FontAwesomeIcon icon={faChevronRight} />,
    wishList: <FontAwesomeIcon icon={faHeart} />,
    cart: <FontAwesomeIcon icon={faShoppingCart} />,
    check: <FontAwesomeIcon icon={faCheck} />,
    truck: <FontAwesomeIcon icon={faTruck} />,
    view: <FontAwesomeIcon icon={faEye} />,
    basket: <FontAwesomeIcon icon={faShoppingBasket} />,
    plus: <FontAwesomeIcon icon={faPlus} />,
    creditCard: <FontAwesomeIcon icon={faCreditCard} />,
    visa: <FontAwesomeIcon icon={faCcVisa} />,
    paypal: <FontAwesomeIcon icon={faPaypal} />,
    delete: <FontAwesomeIcon icon={faTimes} />,
    returns: <FontAwesomeIcon icon={faRedoAlt} />,
    privacy: <FontAwesomeIcon icon={faShieldAlt} />,
    faq: <FontAwesomeIcon icon={faQuestionCircle} />,
    find: <FontAwesomeIcon icon={faMapMarkerAlt} />,
    hamburger: <FontAwesomeIcon icon={faBars} />,
};

export default icons;
